pub(in crate::shell) mod accessible;
mod commands;
pub(in crate::shell) mod export_dialog;
mod global_bar;
mod page_controls;
mod quick_actions;
mod rail;
mod side_panel;
mod tabs;
mod theme;
mod tool_search;

pub(in crate::shell) use accessible::install_keybindings as install_a11y_keybindings;
pub(in crate::shell) use commands::{command_defaults, command_for_id};
pub(in crate::shell) use export_dialog::install_keybindings as install_export_keybindings;
pub(in crate::shell) use global_bar::install_native_menus;
pub(in crate::shell) use global_bar::{MenuAvailability, MenuState, RegistryFacts, RunCommand};
pub(in crate::shell) use quick_actions::QuickAction;
pub(in crate::shell) use tabs::ShellFrame;
pub(in crate::shell) use theme::{ShellViewState, ThemeTokens};
pub(in crate::shell) use tool_search::install_keybindings as install_search_keybindings;
pub(in crate::shell) use tool_search::SearchInput;
