//! Corpus discovery for test targets, in one place.
//!
//! Most of `corpus/` is gitignored: `external/` is fetched, `malformed/` and
//! `bench/` are generated, and only `seeds/` is committed. A test that cannot
//! find what it needs has two honest answers and no third one: say so and
//! return, or fail. Which one it gives is the caller's environment, not the
//! caller's code - [`missing`] fails when `ONIONSKIN_CORPUS_REQUIRED` is set,
//! and CI sets it on the re-run step that exists to turn a skip into a
//! failure.
//!
//! This crate exists because that rule was written out six times over -
//! `cos/tests/common`, `content/tests/common`, `core/tests/search.rs`,
//! `core/tests/panes.rs`, `core/benches/harness` and
//! `codecs-common/tests/roundtrip.rs` - and in none of them anywhere the app
//! or plugin test targets could reach it. Their fixtures are the ones CI has
//! never seen. Those six stay where they are; this is what a new caller uses
//! instead of becoming a seventh.

use std::path::{Path, PathBuf};

// Deliberately not here: a recursive `pdfs_in`, which the four existing
// helpers each carry. It belongs in this crate the moment a target that walks
// a corpus directory reaches for it, and there is not one yet.

/// Root of the shared corpus: `$ONIONSKIN_CORPUS`, else `<workspace>/corpus`.
///
/// A set `ONIONSKIN_CORPUS` that is not a directory is a typo, and reading it
/// as "unset" would run the whole suite against the repository's own corpus
/// while the caller believed it was running against another one. It fails
/// instead.
///
/// The fallback is this crate's own manifest directory two levels up, which is
/// the workspace root for as long as this crate lives under `crates/`. Nothing
/// derives it from the *caller's* manifest, which is how a helper copied into
/// a plugin target ends up pointing one directory too high.
pub fn corpus_root() -> Option<PathBuf> {
    if let Some(from_env) = std::env::var_os("ONIONSKIN_CORPUS") {
        let path = PathBuf::from(from_env);
        assert!(
            path.is_dir(),
            "ONIONSKIN_CORPUS is set to {}, which is not a directory",
            path.display()
        );
        return Some(path);
    }
    let corpus = workspace_root().join("corpus");
    corpus.is_dir().then_some(corpus)
}

/// Returns the corpus subdirectory, or `None` after [`missing`] has had its
/// say.
pub fn corpus_dir(relative: &str) -> Option<PathBuf> {
    let Some(root) = corpus_root() else {
        return missing("no corpus found; set ONIONSKIN_CORPUS to the corpus directory");
    };
    let dir = root.join(relative);
    if !dir.is_dir() {
        return missing(&format!("{} is absent (it is gitignored)", dir.display()));
    }
    Some(dir)
}

/// Reports an absent corpus: a loud skip normally, a failure under
/// `ONIONSKIN_CORPUS_REQUIRED`.
pub fn missing(why: &str) -> Option<PathBuf> {
    if std::env::var_os("ONIONSKIN_CORPUS_REQUIRED").is_some() {
        panic!("corpus required but {why}");
    }
    eprintln!("SKIPPED: {why}");
    None
}

/// One of the committed seeds under `corpus/seeds`.
///
/// Not a lookup, so it never skips: the seeds are in the repository. It goes
/// through [`corpus_root`] so `ONIONSKIN_CORPUS` moves them along with
/// everything else, and it names the root it looked in, because a corpus
/// pointed elsewhere is the way this stops being a broken checkout and starts
/// being a wrong environment.
pub fn seed(name: &str) -> PathBuf {
    let root = corpus_root()
        .unwrap_or_else(|| panic!("no corpus found; set ONIONSKIN_CORPUS to the corpus directory"));
    let path = root.join("seeds").join(name);
    assert!(
        path.is_file(),
        "{} holds no seed {name}, so the corpus root is wrong rather than incomplete",
        root.display()
    );
    path
}

/// One of the committed encrypted fixtures under `corpus/encrypted`.
///
/// Like [`seed`], not a lookup: the fixtures are in the repository, so this
/// never skips. They are committed rather than fetched because an encrypted
/// fixture cannot be regenerated byte for byte - AES needs a random IV - and
/// because a suite proving the encrypted-source rule must not be able to pass
/// over an empty directory.
pub fn encrypted_fixture(name: &str) -> PathBuf {
    committed("encrypted", name, "run corpus/make-encrypted.py")
}

/// One of the committed page-organization fixtures under `corpus/organize`.
///
/// Committed for the same reason as the encrypted ones: the importer's render
/// comparison is the only test that catches a one-level-deep importer, and a
/// fixture CI never fetches is an assertion CI never runs.
pub fn organize_fixture(name: &str) -> PathBuf {
    committed("organize", name, "run corpus/make-organize.py")
}

/// A committed fixture: never skips, and names the generator when it is absent.
fn committed(dir: &str, name: &str, remedy: &str) -> PathBuf {
    let root = corpus_root()
        .unwrap_or_else(|| panic!("no corpus found; set ONIONSKIN_CORPUS to the corpus directory"));
    let path = root.join(dir).join(name);
    assert!(
        path.is_file(),
        "{} holds no {dir} fixture {name}; {remedy}",
        root.display()
    );
    path
}

fn workspace_root() -> &'static Path {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let root = manifest
        .parent()
        .and_then(Path::parent)
        .expect("this crate sits two levels under the workspace root");
    assert!(
        root.join("Cargo.toml").is_file(),
        "{} is not the workspace root, so every corpus lookup would resolve one directory off",
        root.display()
    );
    root
}
