[package]
name = "onionskin-tools-accessibility"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
onionskin-content.workspace = true
onionskin-core.workspace = true
onionskin-cos.workspace = true
onionskin-plugin-api.workspace = true
